### ISSUE TITLE
`{1?}` が動いていないかもしれない

### ISSUE THREAD

**Issue by mika-f** [mika-f/centoria#1]

**Comment by mika-f** [comment]
こう言うので起きてる

```toml
[test]
runas = 'function'
command = '''
tail --lines=200 -f /var/log/{0} | lltsv -k a,b,{1?}
'''
```

```bash
> cet test nginx/error.log
Error: required parameter(s) is missing, please use `show` subcommand for checking parameters
```
