### ISSUE TITLE
設定でコマンドを実行するディレクトリを指定したい

### ISSUE THREAD

**Issue by odanado** [mika-f/centoria#6]
```toml
[hoge]
runas = 'function'
command = 'hoge'
cwd = '/path/to/hoge'
```

的な感じ
